import { mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const PUBLIC_SUFFIX_LIST_URL = "https://publicsuffix.org/list/public_suffix_list.dat";
const OUTPUT_PATH = resolve(import.meta.dir, "../src/shared/public-suffix-data.ts");

type ParsedRules = {
  commit: string;
  exactRules: string[];
  exceptionRules: string[];
  version: string;
  wildcardRules: string[];
};

function getHeaderValue(source: string, prefix: string): string {
  const line = source.split("\n").find((value) => value.startsWith(prefix));
  return line?.slice(prefix.length).trim() ?? "unknown";
}

function parseRules(source: string): ParsedRules {
  const exactRules: string[] = [];
  const wildcardRules: string[] = [];
  const exceptionRules: string[] = [];

  for (const line of source.split("\n")) {
    const rule = line.trim().toLowerCase();

    if (rule.length === 0 || rule.startsWith("//")) {
      continue;
    }

    if (rule.startsWith("*.")) {
      wildcardRules.push(rule.slice(2));
      continue;
    }

    if (rule.startsWith("!")) {
      exceptionRules.push(rule.slice(1));
      continue;
    }

    exactRules.push(rule);
  }

  return {
    commit: getHeaderValue(source, "// COMMIT:"),
    exactRules,
    exceptionRules,
    version: getHeaderValue(source, "// VERSION:"),
    wildcardRules
  };
}

function renderModule({
  commit,
  exactRules,
  exceptionRules,
  version,
  wildcardRules
}: ParsedRules): string {
  return `// Generated by scripts/generate-public-suffix-data.ts.
// Source: ${PUBLIC_SUFFIX_LIST_URL}
// VERSION: ${version}
// COMMIT: ${commit}

export const PUBLIC_SUFFIX_LIST_VERSION = ${JSON.stringify(version)};
export const PUBLIC_SUFFIX_LIST_COMMIT = ${JSON.stringify(commit)};

export const EXACT_RULES_TEXT = ${JSON.stringify(exactRules.join("\n"))};
export const WILDCARD_RULES_TEXT = ${JSON.stringify(wildcardRules.join("\n"))};
export const EXCEPTION_RULES_TEXT = ${JSON.stringify(exceptionRules.join("\n"))};
`;
}

async function main(): Promise<void> {
  const response = await fetch(PUBLIC_SUFFIX_LIST_URL);

  if (!response.ok) {
    throw new Error(`Failed to download public suffix list: ${response.status} ${response.statusText}`);
  }

  const source = await response.text();
  const output = renderModule(parseRules(source));

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await Bun.write(OUTPUT_PATH, output);
}

await main();
